#INCLUDE "plumbing.module"

VAL INT READ.DELAY IS 100:

PROC ReadSensor (VAL INT pin, CHAN INT out!)
  INITIAL INT avr.pin IS board.analog.to.chip(pin):
  WHILE TRUE
    INT reading:
    SEQ
      delay(READ.DELAY)
      adc.base(avr.pin, VCC, reading)
      out ! (reading / 11)
:

PROC TurnOnInRange (VAL INT pin, min, max, CHAN INT in?)
  WHILE TRUE
    INT value:
    SEQ
      digital.mode (pin, OUTPUT)
      in ? value
      IF
        (value >= min) AND (value <= max)
          digital.write(pin, HIGH)
        TRUE
          digital.write(pin, LOW)
:

PROC Fade (VAL INT pin, CHAN INT in?)
  CHAN BYTE lvl:
  PAR
    pwm (pin, lvl?)
    WHILE TRUE
      INT value:
      SEQ
        digital.mode (pin, OUTPUT)
        in ? value
        lvl ! (BYTE ((value * 25) / 10))
:

PROC SetServo (VAL INT pin, CHAN INT in?)
  CHAN BYTE p:
  PAR
    simple.servo (pin , p?)
    INT v:
    WHILE TRUE
      SEQ
        in ? v
        p ! (BYTE ((v * 36) / 21))
:

